<?php

namespace TechForumBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;
use TechForumBundle\Entity\Question;
use TechForumBundle\Entity\User;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository
{
}
